version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: user.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./user_service:/usr/src/app/user_service


  user-db:
    image: postgres:16
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./user-db-data:/var/lib/postgresql/data

volumes:
  user-db:
  user-service: